Find Maximun number added
IdeenNova/B34_GR10_JavaCodingTasks_Reloaded pull request #11
Opened 2024-06-29 13:53 UTC by TahminaZ

2024-06-29 18:06 UTC, ValeriySyutkin requested changes
That doesn't look right. More like a fraction of a code snippet that shows result of the  method without showing actual method implementation itself.    Redo please :)

2024-06-29 22:13 UTC, TahminaZ commented
Well there might be different methods of showing the code. And as per the task requirements it was just asked to show Max number.

2024-06-30 08:44 UTC, ValeriySyutkin commented
Here is  what you should write:
 
    public static int findMax(int[] numbers) {
        if (numbers == null || numbers.length == 0) {
            throw new IllegalArgumentException("Array must not be null or empty");
        }

        int max = numbers[0]; // Initialize max to the first element
        for (int i = 1; i < numbers.length; i++) {
            if (numbers[i] > max) {
                max = numbers[i]; // Update max if current element is greater
            }
        }
        return max;
    }

And you run that method in a "main" method: 

    public static void main(String[] args) {
        int[] numbers = {5, 3, 9, 1, 6};
        int maxNumber = findMax(numbers);
        System.out.println("The maximum number is: " + maxNumber);
    }

2024-07-03 04:12 UTC, ValeriySyutkin approved these changes

2024-07-03 04:12 UTC, merged